use_frameworks!

platform :ios, '10.0'

target 'MKRemoteMetering_Example' do
  pod 'MKRemoteMetering', :path => '../'

  target 'MKRemoteMetering_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
